### ISSUE TITLE
Broken images in chapter 1's cc-template-vars and cc-view-child final projects

### ISSUE THREAD

**Issue by mudassarlodhi** [PacktPublishing/-Angular-Cookbook#21]
As picsum.photos doesnt allow public access to the images now, the gallery images in both the final projects appear broken 

![image](https://user-images.githubusercontent.com/34912771/192100984-ac3566a6-4da1-4070-9e43-18e52fcc9567.png)

**Comment by AhsanAyaz** [comment]
Hey @mudassarlodhi ! Thanks for raising the issue and the PR.
However, I can see the pictures without any issues locally. In all projects. And from the lorempicsum API too. 
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/9844254/200342476-8bd1d6c0-3289-4d80-a84e-e935c809f125.png">

So I'm gonna close this issue since the images work fine.
